export const RISK_FLAG_CODES = {
    HIGH_TREASURY_CONCENTRATION: "HIGH_TREASURY_CONCENTRATION",
    SUDDEN_ACTIVITY_AFTER_DORMANCY: "SUDDEN_ACTIVITY_AFTER_DORMANCY",
    LOW_COUNTERPARTY_DIVERSITY: "LOW_COUNTERPARTY_DIVERSITY",
    ERRATIC_SETTLEMENT_FLOW: "ERRATIC_SETTLEMENT_FLOW",
    TREASURY_FRAGILITY: "TREASURY_FRAGILITY",
    PROFILE_BEHAVIOR_MISMATCH: "PROFILE_BEHAVIOR_MISMATCH",
} as const;